FLAGS = -Wall -g
#HEADERS = allegro5/allegro.h

#default: program

#%.o: %.c $(HEADERS)
#	gcc -c $< -o $@

#program: $(OBJECTS)
#	gcc $(OBJECTS) -o $@ `pkg-config --cflags --libs allegro5`

all:
	make katame 

clean:
	#rm -f $(OBJECTS)
	#rm -f program
	rm -f katame
